const std = @import("std");
const codegen = @import("codegen.zig");

const Allocator = std.mem.Allocator;
const Writer = std.Io.Writer;

const ZigValue = codegen.ZigValue;
const ZigCode = codegen.ZigCode;

pub fn writeProfile(allocator: Allocator, io: std.Io, zig_config: ZigValue, out_path: []const u8) !void {
    const zigCode: ZigCode = blk: {
        var wAlloc: Writer.Allocating = .init(allocator);
        defer wAlloc.deinit();

        try wAlloc.writer.writeAll(
            \\// Generated by vektor. Hand-editing this file is a Sisyphean act —
            \\// your changes will be overwritten on the next `vektor gen`.
            \\
            \\
        );
        try wAlloc.writer.writeAll("const InstallConfig = @import(\"vektor-installation\").InstallConfig;\n\n");
        try wAlloc.writer.writeAll("pub const Config: InstallConfig = ");
        try codegen.writeZigValue(zig_config, &wAlloc.writer);
        try wAlloc.writer.writeAll(";\n");

        break :blk try ZigCode.fmt(allocator, wAlloc.writer.buffered());
    };

    defer zigCode.deinit(allocator);

    const cwd: std.Io.Dir = .cwd();
    return cwd.writeFile(io, .{ .sub_path = out_path, .data = zigCode.source });
}
